### ISSUE TITLE
"The POM is missing"

### ISSUE THREAD

**Issue by vorou** [nskvortsov/teamcity-sdk-maven-plugin#2]
I've created a project from the archetype like this:

    mvn 'archetype:generate' '-DarchetypeRepository=http://repository.jetbrains.com/all' '-DarchetypeArtifactId=teamcity-plugin' '-DarchetypeGroupId=org.jetbrains.teamcity.archetypes' '-DarchetypeVersion=LATEST'

I've added the part from the readme into root [pom](https://gist.github.com/vorou/9586ee63857c9cc2cea3).

`mvn package tc-sdk:start` [results](https://gist.github.com/vorou/18b3ffc6685a9227afac) into `POM missing`, and then `No plugin found for prefix`.

What am I doing wrong?

**Comment by nskvortsov** [comment]
Hello,

Please,  add pluginRepositories section to the pom file.

<pluginRepositories>
<pluginRepository>
<id>JetBrains</id>
<url>http://repository.jetbrains.com/all</url>
</pluginRepository>
</pluginRepositories>

I will update the documentation accordingly.
 24 Май 2015 г. 7:06 пользователь "vorou" <notifications@github.com>
написал:

**Comment by vorou** [comment]
It works, thanks!
